  model: "GigaChat-Plus-preview"
  top_p: 0.8
  scope: "GIGACHAT_API_CORP"
  max_iterations: 10  # max number of generation-reflection steps
  papers:
    - "https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123560715.pdf"
    - "https://arxiv.org/pdf/1801.07698"
  question: "как еще улучшить subcenter arcface loss?"